# This file is generated by Dist::Zilla
# Prereqs are detected automatically. You do not need to edit this file

requires "Test::Harness" => "0";

on 'configure' => sub {
  requires "ExtUtils::MakeMaker" => "0";
};
